# Permalinks
permalink:           pretty

# Setup
title:               Dr Napoleon Book Club
tagline:             Discussion group for readers of Shadow Men and other titles
url:                 http://www.drnapoleonbooks.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Anthony Napoleon Book Club
  url:               https://drnapoleonbookclub.github.io
  email:             drnapoleonbookclub@yandex.com

# Custom vars
version:             0.0.1
github:
  repo:              https://github.com/drnapoleonbookclub

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
